create table items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  description text not null,
  state text not null,
  category text not null
);

alter table items enable row level security;

create policy "Items are visible to everyone."
  on items for select
  using ( true );
